### ISSUE TITLE
Make the long-awaited update to the latest versions

### ISSUE THREAD

**Issue by Fleepe** [feandrad/staff-of-building-reborn#1]
Finally, at least someone took up this mod! It will be just amazing if you also update it to versions 1.19.4 and 1.20.x

**Comment by feandrad** [comment]
Currently working on version 1.20.1, should be up in a couple of days :)

**Comment by feandrad** [comment]
@Fleepe RC1 is out: https://modrinth.com/mod/staff-of-building/versions#all-versions
